name: Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
  schedule:
  - cron: "0 0 * * 0"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Erlang/OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['24', '25', '26']
        rebar3: ['3.22']
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - run: rebar3 do eunit, ct --cover, cover
